package myentertainmentlog.entry.game;

public enum Console {
  // Nintendo
  NES, GAME_BOY, SNES, NINTENDO_64, GAME_BOY_COLOR, NINTENDO_GAMECUBE, GAME_BOY_ADVANCED, NINTENDO_DS, WII,
  NINTENDO_3DS, WII_U, NINTENDO_SWITCH,
  // Sony
  PLAY_STATION_1, PLAY_STATION_2, PLAY_STATION_3, PLAY_STATION_4, PLAY_STATION_5, PSP, PSVITA,
  // SEGA
  MASTER_SYSTEM, MEGA_DRIVE, SEGA_SATURN, DREAMCAST,
  // Microsoft
  XBOX, XBOX_360, XBOX_ONE, XBOX_SERIES,
  // Other
  PC, MOBILE
}
